project 'iOSProject.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSProject' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSProject


pod 'AFNetworking', '~> 3.0'
pod 'YYModel', '~> 1.0.3'
pod 'FMDB', '~> 2.6.2'
pod 'MJRefresh', '~> 3.1.0'
pod 'SDCycleScrollView', '~> 1.65'
pod 'SDWebImage', '~> 3.7.6'
pod 'CYLTabBarController', '~> 1.4.4'
pod 'HYBNetworking', '~>3.1.0'



end
