project 'iOSBlur.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSBlur' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSBlur

pod 'GPUImage', '~> 0.1.7'
pod 'FXBlurView', '~> 1.6.4'

end
